FROM alpine:3.5

MAINTAINER Leon.Xu ( http://github.com/kairyou/ )

# https://github.com/google/skicka

ADD skicka /bin/skicka
ADD skicka.config /root/.skicka.config

# CMD ["skicka"]
ENTRYPOINT ["skicka"]
